### ISSUE TITLE
Rolling window option in tsCV() with xreg

### ISSUE THREAD

**Issue by mkiang** [robjhyndman/forecast#715]
Hi, I may be a bit confused here, but I'm having trouble setting the `window` option in `tsCV()` while also using `xreg`. When not using the `xreg`, the window seems to scan the data correctly:

```
far2 <- function(x, h){forecast(Arima(x, order=c(2,0,0)), h=h)}
e <- tsCV(lynx, far2, h=1, window=30)

fit1   <- Arima(lynx[1:30], order = c(2, 0, 0))
fcast1 <- forecast(fit1, h = 1)
lynx[31] - fcast1$mean[1]; e[30]

# [1] -11.41075
# [1] -11.41075

fit2   <- Arima(lynx[2:31], order = c(2, 0, 0))
fcast2 <- forecast(fit2, h = 1)
lynx[32] - fcast1$mean[1]; e[31]

# [1] -578.658
# [1] -578.658
```

When using the same idea as above, but specifying an `xreg`, it does not work. Any tips on how to write my `forecastfunction` such that I can use a rolling window and `xreg`? It works for the first fit (i.e., before the window starts rolling), but not for other fits. 

```
fc <- function(y, h, xreg)
{
    X <- xreg[1:length(y),]
    if(NROW(xreg) < length(y) + h)
        stop("Not enough xreg data for forecasting")
    newX <- xreg[length(y)+(1:h), ]
    fit <- Arima(y, xreg=X, order = c(1, 0, 0))
    forecast(fit, xreg=newX)
}

set.seed(1)
y <- ts(rnorm(100))
x <- matrix(ts(rnorm(100)),ncol=1)
e <- tsCV(y, fc, xreg=x, window = 20)

fit1   <- Arima(y[1:20], xreg = x[1:20, ], order = c(1, 0, 0))
fcast1 <- forecast(fit1, h = 1, xreg = x[21, ])
y[21] - fcast1$mean[1]; e[20]
# [1] 0.7328816
# [1] 0.7328816

fit2   <- Arima(y[2:21], xreg = x[2:21, ], order = c(1, 0, 0))
fcast2 <- forecast(fit2, h = 1, xreg = x[22, ])
y[22] - fcast2$mean[1]; e[21]
# [1] 0.7791716
# [1] 0.5096576
```

Thanks for any help!

**Comment by robjhyndman** [comment]
Should be ok now. Fixed in https://github.com/robjhyndman/forecast/commit/904028ff5c280e2cf37973a0d60b6726f2cb6235

**Comment by robjhyndman** [comment]
@mitchelloharawild might be able to make the code a bit neater though.

**Comment by anafotina** [comment]
When reproducing the example above, the values between tsCV and manually calculated errors are still different starting from the second step.

**Comment by ncooder** [comment]
@anafotina This works as expected: 
```R
fc <- function(y, h, xreg, newxreg) {
  fit <- Arima(y, xreg = xreg, order = c(1, 0, 0))
  forecast(fit, xreg = newxreg, h = h)
}

**Comment by m-muecke** [comment]
Can be probably closed, I can't reproduce this:

``` r
library(forecast)

# non-xreg case (from original issue)
far2 <- function(x, h) {
  forecast(Arima(x, order = c(2, 0, 0)), h = h)
}
e <- tsCV(lynx, far2, h = 1, window = 30)

fit1 <- Arima(lynx[1:30], order = c(2, 0, 0))
fcast1 <- forecast(fit1, h = 1)
c(manual = lynx[31] - fcast1$mean[1], tsCV = e[30])
#>    manual      tsCV 
#> -11.41075 -11.41075

fit2 <- Arima(lynx[2:31], order = c(2, 0, 0))
fcast2 <- forecast(fit2, h = 1)
c(manual = lynx[32] - fcast2$mean[1], tsCV = e[31])
#>   manual     tsCV 
#> -578.658 -578.658

# xreg case - use xreg/newxreg signature
fc <- function(y, h, xreg, newxreg) {
  fit <- Arima(y, xreg = xreg, order = c(1, 0, 0))
  forecast(fit, xreg = newxreg, h = h)
}

set.seed(1)
y <- ts(rnorm(100))
x <- matrix(ts(rnorm(100)), ncol = 1)
e <- tsCV(y, fc, xreg = x, window = 20)

fit1 <- Arima(y[1:20], xreg = x[1:20, , drop = FALSE], order = c(1, 0, 0))
fcast1 <- forecast(fit1, h = 1, xreg = x[21, , drop = FALSE])
c(manual = y[21] - fcast1$mean[1], tsCV = e[20])
#>    manual      tsCV 
#> 0.7328816 0.7328816

fit2 <- Arima(y[2:21], xreg = x[2:21, , drop = FALSE], order = c(1, 0, 0))
fcast2 <- forecast(fit2, h = 1, xreg = x[22, , drop = FALSE])
c(manual = y[22] - fcast2$mean[1], tsCV = e[21])
#>    manual      tsCV 
#> 0.7791716 0.7791716
```

<sup>Created on 2026-03-01 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
